services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Dev123
      MYSQL_DATABASE: student_db
    # ports:
      # - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  student-api:
    build:
      context: ./Student API
      dockerfile: Dockerfile
    container_name: student-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5096:5096"
    depends_on:
      - mysql
    

  react-app:
    build:
      context: ./reactproject1
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "80:80"
    depends_on:
      - student-api

volumes:
  mysql-data: